[connections.mysql]
dialect = "mysql"
host = "localhost" # またはAWSなどのIPアドレス
port = 3306
database = "your_database_name" # 実際のDB名
username = "your_username"      # ユーザー名
password = "your_password"      # パスワード

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/YOUR_SHEET_ID/edit"  # ここに対象シートのURL
type = "service_account" # 公開シートなら不要
project_id = "xxx"
private_key_id = "xxx"
private_key = "-----BEGIN PRIVATE KEY-----\n..."
client_email = "xxx@yyy.iam.gserviceaccount.com"
client_id = "xxx"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/xxx"